language: dart
jobs:
  include:
  - stage: run tests
    dart: dev
    script:
    - pub get
    - dartfmt -n --set-exit-if-changed .
    # TODO re-enable --fatal-lints once https://github.com/dart-lang/sdk/issues/25551 is fixed
    # - dartanalyzer --fatal-warnings --fatal-hints --fatal-lints .
    - dartanalyzer --fatal-warnings --fatal-hints .
    - pub run test
