name: google_maps
version: 3.4.4
description: >
  With that package you will be able to use Google Maps JavaScript API from Dart
  scripts.
homepage: https://github.com/a14n/dart-google-maps
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  js_wrapping: ^0.5.0
  meta: ^1.1.2
dev_dependencies:
  build_runner: ^1.7.2
  build_web_compilers: ">=1.2.0 <3.0.0"
  html: ^0.13.3
#  js_wrapping_generator: ^0.5.0
  test: ^1.3.0
  package_resolver: 1.0.9 # to avoid similar issue to https://github.com/dart-lang/package_resolver/issues/26
#dependency_overrides:
#   js_wrapping:
#     # git:
#     #   url: https://github.com/a14n/dart-js-wrapping.git
#     #   ref: build
#     #   path: js_wrapping
#     path: ../dart-js-wrapping/js_wrapping
#   js_wrapping_generator:
#     # git:
#     #   url: https://github.com/a14n/dart-js-wrapping.git
#     #   ref: build
#     #   path: js_wrapping_generator
#     path: ../dart-js-wrapping/js_wrapping_generator
